<a href="https://colab.research.google.com/github/SuryARavichan/python-basics/blob/main/PDS_Revision2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

Usage of any() and all()

In [ ]:
a=np.array([1,2,3,-4])
b=np.array([0,2,3,1])
c=a>b

In [ ]:
any(a),all(a)

(True, True)

In [ ]:
print(c)

[ True False False False]


In [ ]:
print(any(c))

True


In [ ]:
print(all(c))

False


usage of where()

In [ ]:
x=np.array([10,21,30,41,50])

In [ ]:
c=np.where(x%2==0,x,0)
print(c)

[10  0 30  0 50]


In [ ]:
p=np.array([10,20,30,40,50])
q=np.array([1,21,3,38,51])
r=np.where(p>q,p,q)
print(r)

[10 21 30 40 51]


usage of nonzero()

In [ ]:
m=np.array([1,2,0,-1,0,6])
np.nonzero(m)

(array([0, 1, 3, 5]),)

In [ ]:
np.min(m),np.argmin(m)

(-1, 3)

In [ ]:
np.max(m),np.argmax(m)

(6, 5)

In [ ]:
y=x

In [ ]:
y[0]=100
y

array([100,  21,  30,  41,  50])

In [ ]:
x

array([100,  21,  30,  41,  50])

In [ ]:
z=x.copy()

In [ ]:
z[0]=200
z

array([200,  21,  30,  41,  50])

In [ ]:
x

array([100,  21,  30,  41,  50])

Usage of flatten()

In [ ]:
mat=np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
mat.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
mat.reshape(-1)

array([1, 2, 3, 4, 5, 6])

Sorting the Matrix

In [ ]:
g=np.array([[5,4,1],[2,7,0]])
g

array([[5, 4, 1],
       [2, 7, 0]])

In [ ]:
np.sort(g)

array([[1, 4, 5],
       [0, 2, 7]])

In [ ]:
np.sort(g,axis=0)

array([[2, 4, 0],
       [5, 7, 1]])

In [ ]:
g.prod(0)

array([10, 28,  0])

In [ ]:
g

array([[5, 4, 1],
       [2, 7, 0]])

In [ ]:
g.prod(1)

array([20,  0])